:new: Lots of new functionality. Closes #2, Closes #4, Closes #7.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,16 +1,15 @@
 #!/bin/bash
 #
-# Add new domains to your setup. This creates the website folder, link to the
-# /etc/hosts file, creates a SSL certificate and sets up a git project for you
-# to begin using.
+# The main install script that sets up and installs everything required
+# by the application.
 # 
-# Copyright: Copyright (C) 2018 Justin Hartman (https://justin.hartman.me)
+# Copyright: Copyright (C) 2018 Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
 # Author   : Justin Hartman <justin@hartman.me> (https://justin.hartman.me)
 # License  : https://opensource.org/licenses/AGPL-3.0 AGPL-3.0
 # Version  : 0.4.0
 # Link     : https://github.com/22digital/Automated-LAMP-trusted-localhost-SSL
 # Link     : https://justin.hartman.me
-# Since    : 0.1.0
+# Since    : 0.4.0
 # 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as
@@ -24,7 +23,7 @@
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
-# 
+#
 
 #######################################
 # Includes the colour palette and
@@ -53,25 +52,21 @@ global_includes ()
 #######################################
 main_application ()
 {
-    source $scripts/enter_domain.sh # Get domain name to be added
-    source $scripts/openssl_config.sh # Add domain to 'openssl.conf' configuration file
-    source $scripts/openssl_command.sh # Create SSL Certificates for the new domain
-    source $scripts/keychain_certificate.sh # Adding new SSL cert to macOS' Keychain
-    source $scripts/hosts_domain.sh # Add new domain to hosts file
-    source $scripts/folder_and_git.sh # Add website folder and initialise git repo
-    source $scripts/git_setup.sh # git initial structure, files and check-in
+    source $scripts/brew_install.sh # Install Homebrew and packages
+    source $scripts/ssl_install.sh # Setup self-signed SSL
+    source $scripts/apache_config.sh # Configure Apache 2
     source $scripts/folder_permissions.sh # Setting correct folder permissions
 
     echo "" >&2
     echo -e "${RED} ----------------------------------------------" >&2
     echo "|                                              |" >&2
-    echo "|  Congratulations! Your domain has been added |" >&2
-    echo "|  and you can begin using it immediately.     |" >&2
-    echo "|  You will find your website folder in the    |" >&2
-    echo "|  `dist/websites/` folder and you can edit    |" >&2
-    echo "|  all your files here. You can access your    |" >&2
-    echo "|  website by visiting the following URL:      |" >&2
-    echo "|  https://${domain}                            " >&2
+    echo "|  Congratulations! You have successfully      |" >&2
+    echo "|  setup your localhost configuration.         |" >&2
+    echo "|  All the files you may need to edit are      |" >&2
+    echo "|  contained in the `/dist/` folder. This      |" >&2
+    echo "|  includes any website you add and access to  |" >&2
+    echo "|  the ssl, adminer, phpmyadmin, error-pages   |" >&2
+    echo "|  and hosts folder.                           |" >&2
     echo "|                                              |" >&2
     echo -e " ---------------------------------------------- ${NOC}\n" >&2
 }
@@ -84,7 +79,7 @@ if ! [ $(id -u) = 0 ]; then
     echo "|                                              |" >&2
     echo "| This needs to be run as root. Please run it  |" >&2
     echo "| again using sudo, as per the command below:  |" >&2
-    echo -e "| ${NOC}${GRY}$ ${NOC}${BLU}sudo ./add_domains                         ${NOC}${RED}|" >&2
+    echo -e "| ${NOC}${GRY}$ ${NOC}${BLU}sudo ./install                             ${NOC}${RED}|" >&2
     echo "|                                              |" >&2
     echo -e " ---------------------------------------------- ${NOC}\n" >&2
     exit 1
